USE [First NF Transport DB]
CREATE TABLE [Pracownicy-zlecenia i urlopy](
    [Imie] varchar(255) NOT NULL,
	[Nazwisko] varchar(255) NOT NULL,
    [Nr. telefonu] varchar(255),
    Pensja int NOT NULL,
    Stanowisko varchar(255) NOT NULL,
	[Miejsce pracy] varchar(255) NOT NULL,
	[Urlop od] date,
	[Urlop do] date,
	[Nr zamowienia] int,  
	[Nazwa dostawcy] varchar(255),
	[Miasto dostawcy] varchar(255),
	[Adres dostawcy] varchar(255),  
	[Nazwa odbiorcy] varchar(255),
	[Miasto odbiorcy] varchar(255),  
	[Adres odbiorcy] varchar(255), 
	Produkt varchar(255),
	[Ilosc produktu] int,
	[Waga jednostkowa produktuc (kg)] float,
	[Termin odebrania] date,
	[Termin dostarczenia] date,
	[Samochod (nr rejestracyjny)] varchar(255),
	[Ladownosc samochodu] int,
	[Stan techniczny samochodu] varchar(255),
	[Dodatek za zlecenie] int,
);